application:
  name: gitlab-runner
  createNamespace: ###ZARF_VAR_GITLAB_RUNNER_CREATE_NAMESPACE###
  namespace: gitlab-runner
  path: chart
  repository: https://repo1.dso.mil/big-bang/product/packages/gitlab-runner.git
  ref:
    tag: 0.52.0-bb.0
  values: |
    ###ZARF_VAR_GITLAB_RUNNER_VALUES###
  dependsOn:
    ###ZARF_VAR_GITLAB_RUNNER_DEPENDS_ON###
